global:
    config_version: 2
    log_level: debug
input:
    type: file

    # 可使用环境变量GROK_INPUT_FILE指定
    path: ./dir/*.log

    # 偏移文件,可使用环境变量GROK_INPUT_POSITION指定
    position_file: ./position.json

    # 偏移文件同步周期
    position_sync_interval: 5s

    # 长度超过max_line_size会被分为多行
    #max_line_size: 128

    # 每个文件 每秒 最多读多少行
    #max_lines_rate_per_file: 128

    # 指定poll_interval_seconds后会采用轮询方式读日志
    #poll_interval_seconds: 3
grok:
    patterns_dir: ./logstash-patterns-core/patterns
    additional_patterns:
    - 'EXIM_MESSAGE [a-zA-Z ]*'
metrics:
    - type: counter
      name: exim_rejected_rcpt_total
      help: Total number of rejected recipients, partitioned by error message.
      match: '%{EXIM_DATE} %{EXIM_REMOTE_HOST} F=<%{EMAILADDRESS}> rejected RCPT <%{EMAILADDRESS}>: %{EXIM_MESSAGE:message}'
      labels:
          error_message: '{{.message}}'
server:
    host: localhost
    port: 8989
