global:
    config_version: 2
    log_level: debug

input:
    # 采集模式，支持下述两种：
    #  1.mixed：软连接采用轮询、常规文件使用inotify
    #  2.poll：所有文件都使用轮询
    collect_mode: mixed

    # 文件类型，支持stdin、file、webhook
    type: file

    # 轮询周期
    poll_interval: 500ms

    # 日志文件路径，支持环境变量和linux通配符
    path:
    - test/*.log
    - test/*.txt

    # 排除哪些文件，支持环境变量和linux通配符
    excludes:
    - test/2.log
    - test/2.txt

    # 偏移文件,支持环境变量
    position_file: ./position.json

    # 偏移文件同步周期
    position_sync_interval: 5s

    # 文件多长时间没有写入后关闭，默认不关闭
    idle_timeout: 60s

    # 行长限制，超过限制，分为多行，默认不限制
    #max_line_size: 128

    # 每个文件 每秒 最多读多少行
    # 若第一秒读超限制，则第二秒不读取，第三秒从文件末尾开始读取(会丢第2秒到第3秒的数据)
    # 该行为由hpcloud/tail提供
    #max_lines_rate_per_file: 128

grok:
    patterns_dir: ./logstash-patterns-core/patterns
    additional_patterns:
    - 'EXIM_MESSAGE [a-zA-Z ]*'

metrics:
    - type: counter
      name: exim_rejected_rcpt_total
      help: Total number of rejected recipients, partitioned by error message.
      match: '%{EXIM_DATE} %{EXIM_REMOTE_HOST} F=<%{EMAILADDRESS}> rejected RCPT <%{EMAILADDRESS}>: %{EXIM_MESSAGE:message}'
      labels:
          error_message: '{{.message}}'

    - type: counter
      name: log_lines_total
      help: Total line number of all .log files but 2.txt.
      match: '.*'
      path:
      - test/*.log
      excludes:
      - test/2.log

    - type: counter
      name: txt_lines_total
      help: Total line number of all .txt files but 2.txt.
      match: '.*'
      path:
      - test/*.txt
      excludes:
      - test/2.txt

server:
    host: 0.0.0.0
    port: 8324
